### PR TITLE
Made link in "Languages" section point to search page of user's repo

### PR DESCRIPTION
**Pull request by sagotch**

### CODE REVIEW

**Comment by u2** [comment]
It looks nice.There is only one small problem, could you rebase it to one commit?

**Comment by sagotch** [comment]
I do no know what went wrong with my rebase, but it seemed to fail and included other's commit. I'll try to fix this later, sorry about that...

**Comment by sagotch** [comment]
Or just copy and past my fix directly into source. It would be faster.

**Comment by bfontaine** [comment]
@sagotch I fixed your PR in #219.

**Comment by sagotch** [comment]
:+1:

**Pull request closed without merging**
